= 抽象工厂模式

The http://en.wikipedia.org/wiki/Abstract_factory_pattern[抽象工厂模式]提供了一种对拥有共同产品族的不同工厂进行封装的一种方法. 它体现了一个标准工厂的意图,即不需要使用代码去确定具体的接口,也不需要了解隐藏的接口后的实现, 而是适用于一组接口,并使用实现了这些接口的某个系列的实现类作为其实现. 

举个例子, 我可能有Button, TextField 和 Scrollbar这三个接口. 我可能会用WindowsButton, MacButton, FlashButton作为Button的实现类. 我可能会用WindowsScrollBar, MacScrollBar and FlashScrollBar作为ScrollBar的实现类. 
使用抽象工厂模式,可以使我选择一个窗口系统(即Windows,Mac,Flash),我希望只选择一次,然后每次写到相关的代码时总是引用到这个接口,而且这个接口的实现类总是和窗口系统相适应(即所有的控件都来自同一个窗口系统).

== 示例

假设我们希望写个游戏系统. 我们可能会注意到很多游戏都拥有相似的功能和控制.

我们决定将这些游戏共有的代码和每个游戏特有的代码分配到不同的类中.

首先,我们看一看http://en.wikipedia.org/wiki/Two-Up[Two-up]游戏特有的代码.

[source,groovy]
----
include::{projectdir}/src/spec/test/DesignPatternsTest.groovy[tags=abstract_factory_example1,indent=0]
----

现在,我们看一下猜数字游戏所特有的代码:

[source,groovy]
----
include::{projectdir}/src/spec/test/DesignPatternsTest.groovy[tags=abstract_factory_example2,indent=0]
----

现在,写我们的工厂代码:

[source,groovy]
----
include::{projectdir}/src/spec/test/DesignPatternsTest.groovy[tags=abstract_factory_code,indent=0]
----

抽象工厂模式中最重要的部分就是允许选择一类族(entire family of conrete classes)作为这些工厂的实现类.

抽象工厂模式是这样使用的:

[source,groovy]
----
include::{projectdir}/src/spec/test/DesignPatternsTest.groovy[tags=abstract_factory_usage,indent=0]
----

注意:第一行配置了我们将会使用哪一类族(family)的游戏实现类.我们通过第一行代码展示的工厂属性,选择具体使用哪一类族这一过程并不重要.我们可以使用另一种等价的方式使用这种模式,比如,我们可以询问用户想玩哪一种游戏,或者使用环境设置来觉得进行哪总游戏等等.


按照我们的代码,游戏运行起来会像这样:

----
Welcome to the twoup game, you start with $1000
You have 1000, how much would you like to bet?
300
Draw
You have 1000, how much would you like to bet?
700
You win
You have 1700, how much would you like to bet?
1700
You lose
Sorry, you have no money left, goodbye
----

如果对第一行的代码做改动 ++GameFactory.factory = guessFactory++, 那么示例程序运行起来会是这个样子:

-------------------------------------------------------------------
Welcome to the guessing game, my secret number is between 1 and 100
Enter a number between 1 and 100
75
Enter a number between 1 and 75
35
Enter a number between 1 and 35
15
Enter a number between 1 and 15
5
Enter a number between 5 and 15
10
Correct
-------------------------------------------------------------------